# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dark-xmera-rrhh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'npm install and build'

  - task: CopyFiles@2
    inputs:
      Contents: 'package*.json'
      TargetFolder: 'dist'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'dist'
      customCommand: 'ci --production'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: 'dist.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist.zip'
      ArtifactName: 'NestDemo'
      publishLocation: 'Container'
